server:
  port: 9001

spring:
  application:
    name: ihrm-company
  redis:
    host: 127.0.0.1
    port: 6379
    password: DoItYun.123
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true