server:
  port: 9006

spring:
  application:
    name: ihrm-com.ihrm.salarys

  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    hikari:
      maximum-pool-size: 2
  redis:
    host: 127.0.0.1
    port: 6379
    password: DoItYun.123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    preferIpAddress : true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
